/*
 * Arvind Nagabhirava
 * Employee Management System - 2019
 */
package employeemark2;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ArvindNagabhirava
 */
public class FTEProfile extends javax.swing.JFrame {
private static FTE foundEmp;
private static JTable employeeTable;

    /**
     * Creates new form FTEProfile
     */
    // Requires an employee to fill in the fields when the frame is instantiated. 
    public FTEProfile(FTE initEmp,JTable employeeTable) {
        this.employeeTable = employeeTable;
        initComponents();
        place();
        this.foundEmp = initEmp;
        enumE.setText(Integer.toString(initEmp.getEmployeeNumber()));
        yrsalE.setText(Double.toString(initEmp.getYearlySalary()));
        drateE.setText(Double.toString(initEmp.getDeductionsRate()));
        double netinc = initEmp.calcAnnualNetIncome(initEmp);
        netinc = (java.lang.Math.round(netinc * 100) / 100.0);        
        netincE.setText(Double.toString(netinc));
        
        //converts sex and work location which are stored as integers, into strings. 
        if (initEmp.getSex() == 0){
            sexE.setText("Male");
        }
        if (initEmp.getSex() == 1){
            sexE.setText("Female");
        }
        if (initEmp.getSex() == 2){
            sexE.setText("Non Binary");
        }
        
        if (initEmp.getWorkLocation() == 1){
            wlocE.setText("Chicago");
        }
        if (initEmp.getWorkLocation() == 2){
            wlocE.setText("New York");
        }
        if (initEmp.getWorkLocation() == 3){
            wlocE.setText("Toronto");
        }
        empLName.setText(initEmp.getLastName());
        empFName.setText(initEmp.getFirstName());
        
        initMouseListener();
    
    }
     static Point mouseDownCompCoords;
    
     //makes window draggable
     private void initMouseListener() {
        try {
            this.addMouseListener(new MouseListener() {
                public void mouseReleased(MouseEvent e) {
                    mouseDownCompCoords = null;
                }

                public void mousePressed(MouseEvent e) {
                    mouseDownCompCoords = e.getPoint();
                }

                public void mouseExited(MouseEvent e) {
                }

                public void mouseEntered(MouseEvent e) {
                }

                public void mouseClicked(MouseEvent e) {
                }
            });

            this.addMouseMotionListener(new MouseMotionListener() {
                public void mouseMoved(MouseEvent e) {
                }

                public void mouseDragged(MouseEvent e) {
                    Point currCoords = e.getLocationOnScreen();
                    setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
                }
            });
        } catch (Exception e) {
            //Silence
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editEmployee = new javax.swing.JButton();
        enumE = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        drateE = new javax.swing.JLabel();
        wlocE = new javax.swing.JLabel();
        yrsalE = new javax.swing.JLabel();
        sexE = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        netincE = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        sexE1 = new javax.swing.JLabel();
        empLName = new javax.swing.JLabel();
        empFName = new javax.swing.JLabel();
        exitButtonTop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel7.setText("Employee Number");

        jLabel12.setText("Deductions Rate");

        jLabel8.setText("Work Location");

        jLabel13.setText("Yearly Salary");

        jLabel14.setText("Gender");

        editEmployee.setText("Edit Employee");
        editEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeActionPerformed(evt);
            }
        });

        enumE.setText("Employee Number");

        removeButton.setText("Remove Employee");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        drateE.setText("Deductions Rate");

        wlocE.setText("Work Location");

        yrsalE.setText("Yearly Salary");

        sexE.setText("Gender");

        jLabel17.setText("Net Income");

        netincE.setText("Net Income");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Work Status");

        sexE1.setText("Full Time");

        empLName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        empLName.setText("Firstname");

        empFName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        empFName.setText("Firstname");

        exitButtonTop.setText("X");
        exitButtonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonTopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButtonTop))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexE1)
                                    .addComponent(enumE)
                                    .addComponent(drateE)
                                    .addComponent(wlocE)
                                    .addComponent(yrsalE)
                                    .addComponent(sexE)
                                    .addComponent(netincE)))
                            .addComponent(empLName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empFName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(editEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exitButtonTop)
                .addGap(18, 18, 18)
                .addComponent(empFName)
                .addGap(6, 6, 6)
                .addComponent(empLName)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enumE)
                        .addGap(6, 6, 6)
                        .addComponent(yrsalE)
                        .addGap(6, 6, 6)
                        .addComponent(drateE)
                        .addGap(6, 6, 6)
                        .addComponent(netincE)
                        .addGap(6, 6, 6)
                        .addComponent(wlocE)
                        .addGap(6, 6, 6)
                        .addComponent(sexE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(sexE1))
                .addGap(41, 41, 41)
                .addComponent(exitButton)
                .addGap(6, 6, 6)
                .addComponent(editEmployee)
                .addGap(6, 6, 6)
                .addComponent(removeButton)
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeActionPerformed
        // TODO add your handling code here:

        new EditFTE((FTE) foundEmp,employeeTable).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editEmployeeActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        LoginPage.getHashTable().removeFromTable(foundEmp.getEmployeeNumber());
        JOptionPane.showMessageDialog(null, "Successfully removed " + foundEmp.getFirstName() +" "+ foundEmp.getLastName());
        LoginPage.getHashTable().fillTable(employeeTable);
        this.dispose();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void exitButtonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonTopActionPerformed
this.dispose();
    }//GEN-LAST:event_exitButtonTopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTEProfile(foundEmp,employeeTable).setVisible(true);
            }
        });
    }
    
    private void place(){
        /*the method "place" places this jframe to the right of the home page so the user can see the entire database as well as the 
        individual profile while searching. */
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((((dim.width - 1062)/2)+751), (dim.height - 550)/2);
        this.setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drateE;
    private javax.swing.JButton editEmployee;
    private javax.swing.JLabel empFName;
    private javax.swing.JLabel empLName;
    private javax.swing.JLabel enumE;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButtonTop;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel netincE;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel sexE;
    private javax.swing.JLabel sexE1;
    private javax.swing.JLabel wlocE;
    private javax.swing.JLabel yrsalE;
    // End of variables declaration//GEN-END:variables
}
