package employeemark2;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * Arvind Nagabhirava
 * Employee Management System - 2019
 */
/**
 *
 * @author ArvindNagabhirava
 */
public class PTEProfile extends javax.swing.JFrame {

    private static PTE foundEmp;
    private static JTable employeeTable;

    /**
     * Creates new form EmployeeProfile
     */
    
    //instantiation requires a Part time employee to fill in the profile. 
    public PTEProfile(PTE initEmp,JTable employeeTable) {
        this.employeeTable = employeeTable;
        initComponents();
        place();
        this.foundEmp = initEmp;
        enumE.setText(Integer.toString(initEmp.getEmployeeNumber()));
        hrwgE.setText(Double.toString(initEmp.getHourlyWage()));
        wkyrE.setText(Double.toString(initEmp.getWeeksPerYear()));
        hrwkE.setText(Double.toString(initEmp.getHoursPerWeek()));
        drateE.setText(Double.toString(initEmp.getDeductionsRate()));
        double netinc = initEmp.getHourlyWage() * initEmp.getHoursPerWeek() * initEmp.getWeeksPerYear() * ((100 - initEmp.getDeductionsRate()) / 100);
        netinc = (java.lang.Math.round(netinc * 100) / 100.0);
        netincE.setText(Double.toString(netinc));
        if (initEmp.getSex() == 0) {
            sexE.setText("Male");
        }
        if (initEmp.getSex() == 1) {
            sexE.setText("Female");
        }
        if (initEmp.getSex() == 2) {
            sexE.setText("Non Binary");
        }

        if (initEmp.getWorkLocation() == 1) {
            wlocE.setText("Chicago");
        }
        if (initEmp.getWorkLocation() == 2) {
            wlocE.setText("New York");
        }
        if (initEmp.getWorkLocation() == 3) {
            wlocE.setText("Toronto");
        }
        empLName.setText(initEmp.getLastName());
        empFName.setText(initEmp.getFirstName());

        initMouseListener();
    }
   
    //makes the window draggable
    static Point mouseDownCompCoords;

    private void initMouseListener() {
        try {
            this.addMouseListener(new MouseListener() {
                public void mouseReleased(MouseEvent e) {
                    mouseDownCompCoords = null;
                }

                public void mousePressed(MouseEvent e) {
                    mouseDownCompCoords = e.getPoint();
                }

                public void mouseExited(MouseEvent e) {
                }

                public void mouseEntered(MouseEvent e) {
                }

                public void mouseClicked(MouseEvent e) {
                }
            });

            this.addMouseMotionListener(new MouseMotionListener() {
                public void mouseMoved(MouseEvent e) {
                }

                public void mouseDragged(MouseEvent e) {
                    Point currCoords = e.getLocationOnScreen();
                    setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
                }
            });
        } catch (Exception e) {
            //Silence
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        empLName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        enumE = new javax.swing.JLabel();
        drateE = new javax.swing.JLabel();
        wlocE = new javax.swing.JLabel();
        hrwgE = new javax.swing.JLabel();
        sexE = new javax.swing.JLabel();
        wkyrE = new javax.swing.JLabel();
        hrwkE = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        netincE = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        editEmployee = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        empFName = new javax.swing.JLabel();
        exitButtonTop = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("Add Part Time Employee");

        jLabel1.setText("Employee Number");

        jLabel11.setText("Deductions Rate");

        jLabel2.setText("First Name");

        jLabel3.setText("Hourly Wage");

        jLabel4.setText("Last Name");

        jLabel5.setText("Weeks Per Year");

        jLabel6.setText("Hours Per Week");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        empLName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        empLName.setText("Firstname");

        jLabel7.setText("Employee Number");

        jLabel12.setText("Deductions Rate");

        jLabel8.setText("Work Location");

        jLabel13.setText("Hourly Wage");

        jLabel14.setText("Gender");

        jLabel15.setText("Weeks Per Year");

        jLabel16.setText("Hours Per Week");

        enumE.setText("Employee Number");

        drateE.setText("Deductions Rate");

        wlocE.setText("Work Location");

        hrwgE.setText("Hourly Wage");

        sexE.setText("Gender");

        wkyrE.setText("Weeks Per Year");

        hrwkE.setText("Hours Per Week");

        jLabel17.setText("Net Income");

        netincE.setText("Net Income");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        editEmployee.setText("Edit Employee");
        editEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeActionPerformed(evt);
            }
        });

        removeButton.setText("Remove Employee");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Work Status");

        jLabel19.setText("Part Time");

        empFName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        empFName.setText("Firstname");

        exitButtonTop.setText("X");
        exitButtonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonTopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitButtonTop, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enumE)
                                    .addComponent(drateE)
                                    .addComponent(wlocE)
                                    .addComponent(jLabel19)
                                    .addComponent(hrwgE)
                                    .addComponent(sexE)
                                    .addComponent(wkyrE)
                                    .addComponent(hrwkE)
                                    .addComponent(netincE)))
                            .addComponent(empLName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empFName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exitButtonTop)
                .addGap(18, 18, 18)
                .addComponent(empFName)
                .addGap(4, 4, 4)
                .addComponent(empLName)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(enumE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hrwgE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(hrwkE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(wkyrE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(drateE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(netincE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(wlocE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sexE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(43, 43, 43)
                .addComponent(exitButton)
                .addGap(6, 6, 6)
                .addComponent(editEmployee)
                .addGap(6, 6, 6)
                .addComponent(removeButton)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void editEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeActionPerformed
        // TODO add your handling code here:

        new EditPTE((PTE) foundEmp,employeeTable).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_editEmployeeActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        LoginPage.getHashTable().removeFromTable(foundEmp.getEmployeeNumber());
        JOptionPane.showMessageDialog(null, "Successfully removed " + foundEmp.getFirstName() + " " + foundEmp.getLastName());
        LoginPage.getHashTable().fillTable(employeeTable);
        this.dispose();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void exitButtonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonTopActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonTopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PTEProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PTEProfile(foundEmp,employeeTable).setVisible(true);
            }
        });
    }

    private void place() {
        /*the method "place" places this jframe to the right of the home page so the user can see the entire database as well as the 
        individual profile while searching. */
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(((dim.width - 1062) / 2) + 751, (dim.height - 550) / 2);
        this.setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drateE;
    private javax.swing.JButton editEmployee;
    private javax.swing.JLabel empFName;
    private javax.swing.JLabel empLName;
    private javax.swing.JLabel enumE;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButtonTop;
    private javax.swing.JLabel hrwgE;
    private javax.swing.JLabel hrwkE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel netincE;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel sexE;
    private javax.swing.JLabel wkyrE;
    private javax.swing.JLabel wlocE;
    // End of variables declaration//GEN-END:variables
}
